# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-21 03:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_favorite_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favorite',
            name='article',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterModelTable(
            name='tags',
            table='tags',
        ),
    ]
