# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-04 07:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20171221_0353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='reddit_id',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
